### ISSUE TITLE
Text editors not working in actors and items

### ISSUE THREAD

**Issue by ghost** [stillday/Tiny-D6-System-for-Foundry-VTT-#12]
Hello,

I just discoverd Tiny D6 and you rule-system for Foundry last week and have been using it to build a campaign, but while creating Items within the system I noticed that the text editors of Actors and Items don't save anything and give the following errors:

> Uncaught (in promise) Error: data.description is not an active editor name!
> [Detected 1 package: system:tinyd6]
>     at TinyD6ItemSheet.saveEditor (foundry.js:6060:46)
>     at jR.save_onsavecallback (TinyD6ItemSheet.js:70:46)
>     at plugin.min.js:4:1197
>     at jR.<anonymous> (plugin.min.js:4:1412)
>     at commands.exec.<computed> (tinymce.min.js:4:358670)
>     at iR.execCommand (tinymce.min.js:4:358116)
>     at jR.execCommand (tinymce.min.js:4:383782)
>     at Object.onAction (plugin.min.js:4:842)
>     at theme.min.js:4:261255
>     at theme.min.js:4:118394
>     at theme.min.js:4:261224
>     at theme.min.js:4:29516
>     at N (theme.min.js:4:2455)
>     at run (theme.min.js:4:29501)
>     at theme.min.js:4:30368
>     at theme.min.js:4:782
>     at theme.min.js:4:139333
>     at B.fold (theme.min.js:4:1075)
>     at fx (theme.min.js:4:139241)
>     at bx (theme.min.js:4:139633)
>     at vx (theme.min.js:4:139720)
>     at theme.min.js:4:141481
>     at theme.min.js:4:37522
>     at li (theme.min.js:4:38286)
>     at Object.triggerEvent (theme.min.js:4:141470)
>     at Cr (theme.min.js:4:25368)
>     at xr (theme.min.js:4:25213)
>     at Sr (theme.min.js:4:25276)
>     at e (theme.min.js:4:86243)
>     at theme.min.js:4:30368
>     at theme.min.js:4:782
>     at theme.min.js:4:139333
>     at B.fold (theme.min.js:4:1075)
>     at fx (theme.min.js:4:139241)
>     at bx (theme.min.js:4:139633)
>     at vx (theme.min.js:4:139720)
>     at theme.min.js:4:141389
>     at theme.min.js:4:141410
>     at theme.min.js:4:37522
>     at li (theme.min.js:4:38286)
>     at Object.triggerEvent (theme.min.js:4:141359)
>     at theme.min.js:4:138209
>     at HTMLDivElement.<anonymous> (theme.min.js:4:13954)
> foundry.js:5099 Foundry VTT | Rendering TinyD6ItemSheet
> commons.js:1703 Error: You are accessing the Item#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logV10CompatibilityWarning (commons.js:6642:14)
>     at get data [as data] (commons.js:6542:24)
>     at get template [as template] (TinyD6ItemSheet.js:11:65)
>     at TinyD6ItemSheet._renderInner (foundry.js:5271:42)
>     at TinyD6ItemSheet._renderInner (foundry.js:5833:30)
>     at TinyD6ItemSheet._render (foundry.js:5114:30)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at lookupProperty (handlebars.min.js:27:16153)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:21:281)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:6948:10)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5271:16)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5833:18)
>     at async TinyD6ItemSheet._render (foundry.js:5114:19)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at lookupProperty (handlebars.min.js:27:16153)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:23:281)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:6948:10)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5271:16)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5833:18)
>     at async TinyD6ItemSheet._render (foundry.js:5114:19)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at lookupProperty (handlebars.min.js:27:16153)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:25:142)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:6948:10)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5271:16)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5833:18)
>     at async TinyD6ItemSheet._render (foundry.js:5114:19)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at lookupProperty (handlebars.min.js:27:16153)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:27:142)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:6948:10)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5271:16)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5833:18)
>     at async TinyD6ItemSheet._render (foundry.js:5114:19)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at lookupProperty (handlebars.min.js:27:16153)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:29:514)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:6948:10)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5271:16)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5833:18)
>     at async TinyD6ItemSheet._render (foundry.js:5114:19)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: The content option for the editor handlebars helper has been deprecated. Please pass the content in as the first option to the helper and ensure it has already been enriched by TextEditor.enrichHTML if necessary
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at Object.logCompatibilityWarning (commons.js:1692:19)
>     at Object.editor (foundry.js:7080:21)
>     at Object.c (handlebars.min.js:27:19853)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:29:145)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:6948:10)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5271:16)
>     at async TinyD6ItemSheet._renderInner (foundry.js:5833:18)
>     at async TinyD6ItemSheet._render (foundry.js:5114:19)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing the Item#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logV10CompatibilityWarning (commons.js:6642:14)
>     at get data [as data] (commons.js:6542:24)
>     at TinyD6ItemSheet._activateEditor (TinyD6ItemSheet.js:66:56)
>     at HTMLDivElement.<anonymous> (TinyD6ItemSheet.js:26:71)
>     at Function.each (jquery.min.js:2:3003)
>     at S.fn.init.each (jquery.min.js:2:1481)
>     at TinyD6ItemSheet.activateListeners (TinyD6ItemSheet.js:26:49)
>     at TinyD6ItemSheet._render (foundry.js:5138:10)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at getProperty (commons.js:2161:41)
>     at TinyD6ItemSheet._activateEditor (TinyD6ItemSheet.js:66:32)
>     at HTMLDivElement.<anonymous> (TinyD6ItemSheet.js:26:71)
>     at Function.each (jquery.min.js:2:3003)
>     at S.fn.init.each (jquery.min.js:2:1481)
>     at TinyD6ItemSheet.activateListeners (TinyD6ItemSheet.js:26:49)
>     at TinyD6ItemSheet._render (foundry.js:5138:10)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing the Item#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logV10CompatibilityWarning (commons.js:6642:14)
>     at get data [as data] (commons.js:6542:24)
>     at TinyD6ItemSheet._activateEditor (TinyD6ItemSheet.js:66:56)
>     at HTMLDivElement.<anonymous> (foundry.js:5860:67)
>     at Function.each (jquery.min.js:2:3003)
>     at S.fn.init.each (jquery.min.js:2:1481)
>     at TinyD6ItemSheet.activateListeners (foundry.js:5860:45)
>     at TinyD6ItemSheet.activateListeners (foundry.js:63902:11)
>     at TinyD6ItemSheet.activateListeners (TinyD6ItemSheet.js:27:15)
>     at TinyD6ItemSheet._render (foundry.js:5138:10)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> commons.js:1703 Error: You are accessing Item#data which has been migrated to Item#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1692:19)
>     at Item._logDataFieldMigration (commons.js:6631:14)
>     at Object.get (commons.js:6595:18)
>     at getProperty (commons.js:2161:41)
>     at TinyD6ItemSheet._activateEditor (TinyD6ItemSheet.js:66:32)
>     at HTMLDivElement.<anonymous> (foundry.js:5860:67)
>     at Function.each (jquery.min.js:2:3003)
>     at S.fn.init.each (jquery.min.js:2:1481)
>     at TinyD6ItemSheet.activateListeners (foundry.js:5860:45)
>     at TinyD6ItemSheet.activateListeners (foundry.js:63902:11)
>     at TinyD6ItemSheet.activateListeners (TinyD6ItemSheet.js:27:15)
>     at TinyD6ItemSheet._render (foundry.js:5138:10)
>     at async TinyD6ItemSheet._render (foundry.js:5822:5)
> logCompatibilityWarning @ commons.js:1703
> foundry.js:56996 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'document')
> [No packages detected]
>     at TextEditor._createTinyMCE (foundry.js:56996:21)
> 

I noticed within the error that there are a lot of deprecated warnings so I am wondering right now if this feature is not yet supported or that this is a bug?

If you need anymore information let me know.
I will be sure to check this issue regulary.

As last apolagies for any spelling mistakes, english is not my first language.

Kind Regards
J.

**Comment by stillday** [comment]
hey,
thank you for reporting.
We took over the repro ourselves (since the original repro is no longer being worked on) and are currently working on all errors and update problems. there is currently a big merge request open, when it's checked we will deploy the whole thing. I can't tell you when the time will come, I understand that it's annoying that not everything is working properly.

**Comment by ghost** [comment]
Hi,
Thank you for your quick answer. It is nice to hear that you are working on it and the problem is known. For now I can work around the problemen and I'm in no hurry. I will wait patiently for the merge and after that I will give it a test run. Thank you for your hard work!

With Regard,
J

**Comment by stillday** [comment]
very much. I hope to be able to write to you soon that everything has been fixed.
regards
J

**Comment by stillday** [comment]
New Version is out now

**Comment by ghost** [comment]
Hi,

I tested it this evening and everything seems to work fine and as expected.
I will start adding full charcters and NPCs this weekend and if I notice anything abnormal I will let you know.
Thank you for your great work.

Regards,
J

![afbeelding](https://user-images.githubusercontent.com/20533654/212199211-6a16507a-d934-449b-85c0-dd45ce4e1440.png)

**Comment by ghost** [comment]
Hey,

I just noticed that these fields in the character actor keep reseting everytime I add a new trait, gear or close the window.
![afbeelding](https://user-images.githubusercontent.com/20533654/212546424-350a60bf-988e-40e0-9a67-984172049254.png)
![afbeelding](https://user-images.githubusercontent.com/20533654/212546791-60be2836-03ee-4f09-bbc8-e549673e2c15.png)

The rest seems to work as it should.

I just wanted to make this known to you.

Regards,
J

**Comment by stillday** [comment]
thanks for the info.
i check it the next days

Regards,
J

**Comment by stillday** [comment]
hotfix is out now

**Comment by stillday** [comment]
i close now this issu. when you find a new one. please open a new issu
